//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int BLMa { get; set; }
        public string SPMa { get; set; }
        public string BLTinNhan { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
